spring:
  application:
    name: yanshi
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driverClassName:  com.mysql.jdbc.Driver

server:
  port: 8010
